---
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
env:
  browser: true
  node: true
  es2022: true
parser: '@typescript-eslint/parser'
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'prettier'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  prettier/prettier: error
  no-useless-catch: off
  no-unused-vars: error
  '@typescript-eslint/no-var-requires': off
